import { memo, useCallback, useMemo } from "react";
import ReactFlow, { Background, Controls, MarkerType, MiniMap, Position, type Edge, type Node } from "reactflow";
import type { ArchitecturePageData, FileSpec } from "@/types";
import type { ArchitectureFilter } from "./DependencyFilterBar";

const positions:Record<string,{x:number;y:number}>={main:{x:370,y:20},wiki:{x:120,y:160},search:{x:360,y:180},utils:{x:590,y:170},client:{x:40,y:330},prompts:{x:610,y:330},ner:{x:820,y:330},datasets:{x:820,y:20},wikidata:{x:0,y:500},wikipedia:{x:240,y:500},llm:{x:540,y:500},azure:{x:820,y:500}};
const colors:Record<string,string>={runtime:"#8b5cf6",retrieval:"#06b6d4",graph:"#f59e0b",utilities:"#64748b",data:"#10b981",external:"#f43f5e"};
const externals=[{id:"wikidata",name:"Wikidata XML-RPC",purpose:"Graph query servers"},{id:"wikipedia",name:"Wikipedia",purpose:"Article evidence"},{id:"llm",name:"LLM API",purpose:"Pruning and reasoning"},{id:"azure",name:"Azure NER",purpose:"Optional entity linking"}];
export const ArchitectureGraph=memo(function ArchitectureGraph({data,selectedId,onSelect,filter}:{data:ArchitecturePageData;selectedId:string;onSelect:(file:FileSpec)=>void;filter:ArchitectureFilter}){
 const visibleFiles=useMemo(()=>data.files.filter(f=>filter==="all"||f.category===filter||filter==="external"&&f.externalCalls.length),[data.files,filter]);
 const ids=useMemo(()=>{const result=new Set(visibleFiles.map(f=>f.id));if(filter==="all"||filter==="external")externals.forEach(e=>result.add(e.id));return result},[visibleFiles,filter]);
 const nodes=useMemo<Node[]>(()=>[...visibleFiles.map(file=>({id:file.id,position:positions[file.id],sourcePosition:Position.Bottom,targetPosition:Position.Top,data:{label:<div title={file.description} className="w-40"><div className="text-[10px] font-bold uppercase tracking-wide opacity-70">{file.category}</div><div className="mt-1 font-mono text-sm font-semibold">{file.name}</div><div className="mt-1 truncate text-[10px] opacity-70">{file.role}</div></div>},style:{border:`2px solid ${colors[file.category]}`,background:selectedId===file.id?`${colors[file.category]}18`:"white",boxShadow:selectedId===file.id?`0 0 0 3px ${colors[file.category]}35`:"0 1px 3px #0001",borderRadius:8,padding:10}})),...externals.filter(e=>ids.has(e.id)).map(e=>({id:e.id,position:positions[e.id],targetPosition:Position.Top,data:{label:<div title={e.purpose} className="w-36"><div className="text-[10px] font-bold uppercase text-rose-600">External service</div><div className="mt-1 text-xs font-semibold">{e.name}</div></div>},style:{border:`2px dashed ${colors.external}`,background:"#fff1f2",borderRadius:8,padding:10}}))],[visibleFiles,ids,selectedId]);
 const edges=useMemo<Edge[]>(()=>data.moduleEdges.filter(e=>ids.has(e.source)&&ids.has(e.target)).map((e,i)=>({id:`${e.source}-${e.target}-${i}`,source:e.source,target:e.target,label:e.type.replace('_',' '),animated:e.type==="external_call",markerEnd:{type:MarkerType.ArrowClosed,color:e.type==="external_call"?"#f43f5e":"#94a3b8"},style:{stroke:e.type==="external_call"?"#f43f5e":"#94a3b8"},labelStyle:{fontSize:9,fill:"#64748b"}})),[data.moduleEdges,ids]);
 const handleNode=useCallback((_:unknown,node:Node)=>{const file=data.files.find(f=>f.id===node.id);if(file)onSelect(file)},[data.files,onSelect]);const nodeColor=useCallback((n:Node)=>n.id===selectedId?"#0891b2":"#cbd5e1",[selectedId]);
 return <div className="h-[570px] overflow-hidden rounded-lg border border-slate-200 bg-white"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{padding:.18}} minZoom={.45} maxZoom={1.8} onNodeClick={handleNode} onlyRenderVisibleElements><Background color="#cbd5e1" gap={20}/><Controls/><MiniMap pannable zoomable nodeColor={nodeColor}/></ReactFlow></div>
});
