import { memo, useCallback, useEffect, useMemo } from "react";
import ReactFlow,{Background,Controls,MarkerType,MiniMap,Position,useReactFlow,type Edge,type Node} from "reactflow";
import type { GraphExample } from "@/types";

const colors={topic:"#7c3aed",entity:"#64748b",expanded:"#0891b2",answer:"#059669"};
const flowOptions={hideAttribution:true};
function GraphCanvas({example,depth,pathOnly,selectedNodeId,selectedEdgeId,fitNonce,onNode,onEdge,onClear}:{example:GraphExample;depth:number;pathOnly:boolean;selectedNodeId:string|null;selectedEdgeId:string|null;fitNonce:number;onNode:(id:string)=>void;onEdge:(id:string)=>void;onClear:()=>void}){
 const {fitView}=useReactFlow(); useEffect(()=>{const timer=window.setTimeout(()=>fitView({padding:.28,duration:250}),50);return()=>window.clearTimeout(timer)},[example.id,depth,pathOnly,fitNonce,fitView]);
 const visibleNodes=useMemo(()=>example.nodes.filter(n=>n.depth<=depth&&(!pathOnly||example.reasoningPath.includes(n.id))),[example.nodes,example.reasoningPath,depth,pathOnly]); const visibleIds=useMemo(()=>new Set(visibleNodes.map(n=>n.id)),[visibleNodes]);
 const nodes=useMemo<Node[]>(()=>visibleNodes.map((n,i)=>{const peers=visibleNodes.filter(x=>x.depth===n.depth),slot=peers.findIndex(x=>x.id===n.id),x=80+n.depth*280,y=55+slot*120-(peers.length-1)*42;const selected=n.id===selectedNodeId,path=example.reasoningPath.includes(n.id);return {id:n.id,position:{x,y},sourcePosition:Position.Right,targetPosition:Position.Left,draggable:true,selectable:true,data:{label:<div className="w-32"><div className="text-[9px] font-bold uppercase tracking-wider opacity-60">{n.entityType}</div><div className="mt-1 text-sm font-bold">{n.label}</div>{n.qid&&<div className="mt-0.5 font-mono text-[9px] opacity-50">{n.qid}</div>}</div>},style:{border:`2px solid ${colors[n.type]}`,borderRadius:12,background:selected?`${colors[n.type]}20`:"white",boxShadow:selected?`0 0 0 4px ${colors[n.type]}33`:path?`0 5px 18px ${colors[n.type]}25`:"0 2px 5px #0f172a12",padding:11,color:"#0f172a"}}}),[visibleNodes,selectedNodeId,example.reasoningPath]);
 const edges=useMemo<Edge[]>(()=>example.edges.filter(e=>e.depth<=depth&&visibleIds.has(e.source)&&visibleIds.has(e.target)&&(!pathOnly||e.inReasoningPath)).map(e=>({id:e.id,source:e.source,target:e.target,label:e.relation,animated:e.inReasoningPath,selectable:true,markerEnd:{type:MarkerType.ArrowClosed,color:e.inReasoningPath?"#f59e0b":"#94a3b8"},style:{stroke:e.id===selectedEdgeId?"#2563eb":e.inReasoningPath?"#f59e0b":"#94a3b8",strokeWidth:e.inReasoningPath?2.5:1.5},labelStyle:{fontSize:10,fontWeight:700,fill:e.inReasoningPath?"#92400e":"#64748b"},labelBgStyle:{fill:"white",fillOpacity:.9}})),[example.edges,depth,pathOnly,selectedEdgeId,visibleIds]);
 const handleNode=useCallback((_:unknown,n:Node)=>onNode(n.id),[onNode]);const handleEdge=useCallback((_:unknown,e:Edge)=>onEdge(e.id),[onEdge]);const nodeColor=useCallback((n:Node)=>colors[example.nodes.find(x=>x.id===n.id)?.type||"entity"],[example.nodes]);
 return <ReactFlow nodes={nodes} edges={edges} fitView onNodeClick={handleNode} onEdgeClick={handleEdge} onPaneClick={onClear} minZoom={.35} maxZoom={2} proOptions={flowOptions} onlyRenderVisibleElements><Background color="#cbd5e1" gap={22}/><Controls/><MiniMap pannable zoomable nodeColor={nodeColor}/></ReactFlow>
}
export const InteractiveGraph=memo(function InteractiveGraph(props:Parameters<typeof GraphCanvas>[0]){return <div className="h-[590px] overflow-hidden rounded-xl border border-slate-200 bg-gradient-to-br from-white to-slate-50 shadow-sm"><GraphCanvas {...props}/></div>});
